product-name: p_spring-cloud-services
network-properties:
  network:
    name: ((network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-properties:
  .properties.config_server_broker_access:
    value: ((config_server_broker_access))
resource-config:
  spring-cloud-services:
    instance_type:
      id: ((spring-cloud-services_instance_type))
    instances: ((spring-cloud-services_instances))
    persistent_disk:
      size_mb: ((spring-cloud-services_persistent_disk_size))
