custom_buildpack: java_buildpack_offline
dataflow_db_plan: db-small
dataflow_db_service: p.mysql
dataflow_disable_public_internet: false
dataflow_messaging_plan: standard
dataflow_messaging_service: p-rabbitmq
dataflow_redis_plan: cache-small
dataflow_redis_service: p.redis
db_service_name: p.mysql
db_service_plan: db-small
p_dataflow_enable_global_access_to_plans: true
skipper_db_plan: db-small
skipper_db_service: p.mysql
