product-name: azure-service-broker
network-properties:
  network:
    name: ((network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-properties:
  .properties.allow_to_generate_names_and_passwords_for_the_missing:
    value: ((allow_to_generate_names_and_passwords_for_the_missing))
  .properties.azure_broker_database_encryption_key:
    value:
      secret: ((azure_broker_database_encryption_key))
  .properties.azure_broker_database_name:
    value: ((azure_broker_database_name))
  .properties.azure_broker_database_password:
    value:
      secret: ((azure_broker_database_password))
  .properties.azure_broker_database_provider:
    value: ((azure_broker_database_provider))
  .properties.azure_broker_database_server:
    value: ((azure_broker_database_server))
  .properties.azure_broker_database_user:
    value: ((azure_broker_database_user))
  .properties.azure_service_broker_enable_global_access_to_plans:
    value: ((azure_service_broker_enable_global_access_to_plans))
  .properties.azure_sqldb_allow_to_create_sql_server:
    value: ((azure_sqldb_allow_to_create_sql_server))
  .properties.azure_sqldb_enable_transparent_data_encryption:
    value: ((azure_sqldb_enable_transparent_data_encryption))
  .properties.client_id:
    value: ((client_id))
  .properties.client_secret:
    value:
      secret: ((client_secret))
  .properties.default_location:
    value: ((default_location))
  .properties.default_parameters_azure_cosmosdb:
    value: ((default_parameters_azure_cosmosdb))
  .properties.default_parameters_azure_docdb:
    value: ((default_parameters_azure_docdb))
  .properties.default_parameters_azure_eventhubs:
    value: ((default_parameters_azure_eventhubs))
  .properties.default_parameters_azure_mysqldb:
    value: ((default_parameters_azure_mysqldb))
  .properties.default_parameters_azure_postgresqldb:
    value: ((default_parameters_azure_postgresqldb))
  .properties.default_parameters_azure_rediscache:
    value: ((default_parameters_azure_rediscache))
  .properties.default_parameters_azure_servicebus:
    value: ((default_parameters_azure_servicebus))
  .properties.default_parameters_azure_sqldb:
    value: ((default_parameters_azure_sqldb))
  .properties.default_parameters_azure_sqldb_failover_group:
    value: ((default_parameters_azure_sqldb_failover_group))
  .properties.default_parameters_azure_storage:
    value: ((default_parameters_azure_storage))
  .properties.default_resource_group:
    value: ((default_resource_group))
  .properties.environment:
    value: ((environment))
  .properties.subscription_id:
    value: ((subscription_id))
  .properties.tenant_id:
    value: ((tenant_id))
resource-config:
  delete-all:
    instance_type:
      id: ((delete-all_instance_type))
  deploy-all:
    instance_type:
      id: ((deploy-all_instance_type))
